# Cache
cache_path: cache
cache_time: 3600

# LSID domains that support full resolution protocol

authority:
 - "aphid.speciesfile.org"
 - "blattodea.speciesfile.org"
 - "coreoidea.speciesfile.org"
 - "orthoptera.speciesfile.org"
 - "irmng.org"
 - "marinespecies.org"
 - "nmbe.ch"

# Rules for LSIDs where the service providing XML is not discoverable using LSID protocol

resolver:
 - 
   domain: indexfungorum.org
   url: "http://www.indexfungorum.org/IXFWebService/Fungus.asmx/NameByKeyRDF?NameLsid={LSID}"
   web: "http://www.indexfungorum.org/Names/NamesRecord.asp?RecordID={ID}"
   
 - 
   domain: "ipni.org"
   url: "https://ipni.org/{LSID}"
   content-type: "application/rdf+xml"
   web: "https://www.ipni.org/{LSID}"
    
 - 
   domain: "organismnames.com"
   url: "http://www.organismnames.com/lsidmetadata.htm?lsid={ID}"
   web: "http://www.organismnames.com/details.htm?lsid={ID}"

 - 
   domain: "zoobank.org"
   url: "https://zoobank.org/NomenclaturalActs.xml/{ID}"
   content-type: "application/rdf+xml"
   web: "https://zoobank.org/{ID}"
 